### ISSUE TITLE
Fix Disorder

### ISSUE THREAD

**Issue by banrovegrie** [banrovegrie/Playing-Games#7]
Put everything finally in the HTML website.

**Comment by MalhotraPulak** [comment]
can you link me the pages i need to put up on the website

**Comment by banrovegrie** [comment]
@PulakIIIT https://www.notion.so/Playing-Games-For-Research-Purposes-872597d5057e4c509f81bbae3e4db04c

**Comment by MalhotraPulak** [comment]
check website boomer
